create table telemetry_ingest_keys (
  id bigint generated by default as identity primary key,
  project_id bigint not null,
  label varchar(255) not null,
  key_hash varchar(128) not null unique,
  active boolean not null default true,
  created_at timestamp not null default current_timestamp,
  last_used_at timestamp,
  constraint fk_ingest_key_project foreign key (project_id) references projects(id) on delete cascade
);

create index idx_telemetry_ingest_keys_project on telemetry_ingest_keys(project_id);

create table telemetry_ingest_events (
  id bigint generated by default as identity primary key,
  project_id bigint not null,
  source varchar(100) not null,
  signal_type varchar(50) not null,
  payload_json text not null,
  received_at timestamp not null default current_timestamp,
  constraint fk_ingest_event_project foreign key (project_id) references projects(id) on delete cascade
);

create index idx_telemetry_ingest_events_project_time on telemetry_ingest_events(project_id, received_at desc);
create index idx_telemetry_ingest_events_type on telemetry_ingest_events(signal_type);
